Migrate repo to Typescript (#46)
* Initial TS migration

- Rename all .js to .ts
- Add //@ts-nocheck to top of TS files
- Add TSConfig file and webpack code for TS

Runtime error
`Uncaught TypeError:
leaflet__WEBPACK_IMPORTED_MODULE_0___default(...).control.locate is not a function` is occuring.

* Fix uncaught typeerrors for .locate and .hash

* Fix touchHelper and polyline errors

* Fix a number of typescript issues

- Had to add a number of if statements to check if var is null
    - These are untested, but chances are if the value was null
      bad things would have happened anyway
- Added lots of `: any`s.

* Add typecheck script, skip node_modules TS check

* Fix edit bug where black line roads wouldn't appear

It seems TS conversion added some object prototypes in some objects for some
reason. This changed the behavior of the `!conditions` statement.

I've changed the statement to be more specific - checking if the object
is empty.

* Improve typescript types further

* Fix missing types for opening_hours

I had used yarn rather than npm locally. Yarn installed 3.7 of
opening_hours, while npm installed 3.6.

3.6 doesn't have the typescript type definitions.

I've changed the version in the package.json to 3.7 and updated the
package-lock.json

I've removed the yarn.lock which I believe I incorrectly committed.

* Return default color when conditions.intervals not defined

Instead of black